### PR TITLE
Corrected The Qbox PlayerData Code

### PR DESCRIPTION
**Pull request by ghost**
Qbox doesn't use exports to get the PlayerData.

Use QBX.PlayerData not exports['qbx_core']:GetPlayerData()

### CODE REVIEW

**Review by Lionh34rt — COMMENTED** [review]
This code will break because QBX is not imported.

Haven't used QBox personally, but looking in qbx_core i found the GetPlayerData export

https://github.com/Qbox-project/qbx_core/blob/main/client/functions.lua#L45

**Comment by Error420Unknown** [comment]
> This code will break because QBX is not imported.
> 
> Haven't used QBox personally, but looking in qbx_core i found the GetPlayerData export
> 
> https://github.com/Qbox-project/qbx_core/blob/main/client/functions.lua#L45

**Comment by ghost** [comment]
> This code will break because QBX is not imported.
> 
> Haven't used QBox personally, but looking in qbx_core i found the GetPlayerData export
> 
> https://github.com/Qbox-project/qbx_core/blob/main/client/functions.lua#L45

Hmm yeah i have been using Qbox for a few months now and never actually thought about going into the code and looking around i just went off based on the docs which that export isn't in the docs.

You can always add '@qbx_core/modules/playerdata.lua' into the shared_scripts in fxmanifest.lua to prevent the code breaking

**Comment by Lionh34rt** [comment]
> > This code will break because QBX is not imported.
> > Haven't used QBox personally, but looking in qbx_core i found the GetPlayerData export
> > https://github.com/Qbox-project/qbx_core/blob/main/client/functions.lua#L45
> 
> Hmm yeah i have been using Qbox for a few months now and never actually thought about going into the code and looking around i just went off based on the docs which that export isn't in the docs.
> 
> You can always add '@qbx_core/modules/playerdata.lua' into the shared_scripts in fxmanifest.lua to prevent the code breaking

No worries!

I'm going to close this PR as it seems unneccesary for me.

If any issues arise, a new one can always be made

**Pull request closed without merging**
