### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by vibewitharyaan**
Added weed lab teleport and weed lab key too which can enable/disable from the shared.lua as I saw many of the members were confused and asking for it.. :)

### CODE REVIEW

**Comment by KingRyuShin** [comment]
Nice update, if you have time for it, you should make it that every card as a "serials" which enable to enter into the person labs insted of sharing it with everybody that has the key, that way team can use it together and people will be able to steal from other player otherwise anyone can just come and get/steal your thing.

just like qb-appartments

**Comment by vibewitharyaan** [comment]
> Nice update, if you have time for it, you should make it that every card as a "serials" which enable to enter into the person labs insted of sharing it with everybody that has the key, that way team can use it together and people will be able to steal from other player otherwise anyone can just come and get/steal your thing.
> 
> just like qb-appartments

I'm a bit confused can you give me an example? Currently, the code is like that those who have the weed lab key with them only can tp... 
Do you want me to make it like some pin code password or something like that?

**Comment by MonkeyWhisper** [comment]
> > Nice update, if you have time for it, you should make it that every card as a "serials" which enable to enter into the person labs insted of sharing it with everybody that has the key, that way team can use it together and people will be able to steal from other player otherwise anyone can just come and get/steal your thing.
> > just like qb-appartments
> 
> I'm a bit confused can you give me an example? Currently, the code is like that those who have the weed lab key with them only can tp... Do you want me to make it like some pin code password or something like that?

Ignore it, this is a good PR, nothing extra is needed. Great job.

People want you to code for them.

**Comment by MonkeyWhisper** [comment]
@3RROR-HUB 

I forgot to ask, can you include this on the read me as a feature and a preview for reference? 

Thanks!

**Comment by vibewitharyaan** [comment]
> @3RROR-HUB
> 
> I forgot to ask, can you include this on the read me as a feature and a preview for reference?
> 
> Thanks!

I already added it on ReadMe

**Comment by MonkeyWhisper** [comment]
> > @3RROR-HUB
> > I forgot to ask, can you include this on the read me as a feature and a preview for reference?
> > Thanks!
> 
> I already added it on ReadMe

Thank you! I missed that

**Pull request merged**
